version: '3.4'

services:
  tasksdb:
    container_name: tasksdb
    environment:
      - MSSQL_SA_PASSWORD=Wfd471Wfd471n9!
      - ACCEPT_EULA="Y"
    restart: always
    ports:
      - "1433:1433"

  taskservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:TaskConnectionString=Server=tasksdb;Database=taskdb;User Id=sa;Password=Wfd471Wfd471n9!;TrustServerCertificate=True;"
      - KEY=ffc424-4werfsd-saef3-srfi45
    ports:
      - "80"
